### ISSUE TITLE
Modded Enemies Support

### ISSUE THREAD

**Issue by Mi6kbuttface** [kirpichyov/LC_EnemiesScanner#9]
Hey, I've been trying to disable certain modded enemies from showing up on the scanner, and I've managed to be able to edit the JSON file to correctly display the names of enemies (i.e PeeperPrefab - Peeper), but when it comes to disabling these enemies in the config files, using either name, (Peeper;PeeperPrefab;) doesn't seem to be working for me. I've tried this with Herobrine, Don't Touch Me, and Football as the entities I'm trying to disable from the scanner.

If there is a proper way of doing this please inform me, but if not could you potentially add support to disable custom enemies?

**Comment by kirpichyov** [comment]
Hi, @Mi6kbuttface! Thanks for reaching out. Yes, looks like there is no ability to disable the moded creatures. But I will have a look into it and will update the mod to add support for modded creatures. Also, I will update the enemy name aliases logic to remove the 'Prefab' suffix so you could just use 'Peeper' etc.

**Comment by kirpichyov** [comment]
Hi, @Mi6kbuttface! Blacklist support for creatures from the mods was introduced in the new version (1.0.6). Also, I have added the information log into the console that shows the name that could be used in the blacklist and the alias config, see [Wiki](https://thunderstore.io/c/lethal-company/p/Kirpichyov/EnemiesScanner/wiki/1444-creature-technical-names/) (I hope it would be helpful). 
I have tested this update with creatures you have mentioned, so I could show the logs examples and the actual names to use in the config:

|Blacklist config name|Alias config name|
|-|-|
|DTMEntity |DTMEntity|
|Roomba |Boomba|
|Herobrine|Herobrine|
|Football|FootballPref|

```
[Info   :Kirpichyov's EnemiesScanner] [Notice] Non vanilla game creature detected! You could use 'Roomba' name in the scanner blacklist config if you want to hide it. For alias config you could use 'Boomba' name.

[Info   :Kirpichyov's EnemiesScanner] [Notice] Non vanilla game creature detected! You could use 'DTMEntity' name in the scanner blacklist config if you want to hide it. For alias config you could use 'DTMEntity' name.

[Info   :Kirpichyov's EnemiesScanner] [Notice] Non vanilla game creature detected! You could use 'Herobrine' name in the scanner blacklist config if you want to hide it. For alias config you could use 'Herobrine' name.

[Info   :Kirpichyov's EnemiesScanner] [Notice] Non vanilla game creature detected! You could use 'Football' name in the scanner blacklist config if you want to hide it. For alias config you could use 'FootballPref' name.
```

The new version of the mod has been published but It will take approximately half an hour now for Thunderstore to index the update so it will be available to download from the mod manager. 

Thanks for your feedback!

**Comment by Mi6kbuttface** [comment]
> Owner
> ###

<3 Love you dude, thank you so much!
